[package]
name = "discfuck_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.11.2"
tokio = { version = "1.19.2", features = ["rt", "rt-multi-thread", "macros"] }
dotenv = "0.15.0"